version: "3"
services:
  # https://hub.docker.com/_/mongo/
  mongo:
    container_name: dc-mongo-whoscored
    env_file:
      - mongo.env
    image: mongo:latest
    networks:
      - mongo
    ports:
      - "127.0.0.1:27019:27017"
    restart: always
    tty: true
    volumes:
      - ./mongo-home:/home/mongodb
      - ./mongo-db:/data/db
      - ./mongo-initdb.d:/docker-entrypoint-initdb.d
  # https://hub.docker.com/_/mongo-express/
  mongo-express:
    container_name: dc-mongodb-express-whoscored
    depends_on:
      - mongo
    env_file:
      - mongo-express.env
    image: mongo-express:latest
    links:
      - mongo
    networks:
      - mongo
    ports:
      - "127.0.0.1:8082:8081"
    restart: always
    tty: true

networks:
  mongo:
    driver: bridge
